stages:
  - build
  - distribute
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG # i.e gitlab.com/gamepod/agent:ef4gb56
  CONTAINER_DEVEL_IMAGE: $CI_REGISTRY_IMAGE:devel # i.e gitlab.com/gamepod/agent:devel
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest # i.e gitlab.com/gamepod/agent:latest
  CONTAINER_RELEASE_VERSIONED: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG # i.e gitlab.com/gamepod/agent:v0.0.1

image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build docker:
  stage: build
  cache:
    paths:
      - image_cache/
  script:
    # Attempt to pull the last image built as a cache
    - docker pull $CONTAINER_DEVEL_IMAGE || true
    # Cache workaround for dind
    - mkdir -p image_cache/
    - export IMAGE_FILE=$CONTAINER_DEVEL_IMAGE
    - '[ -f "$IMAGE_FILE" ] && docker load -i "$IMAGE_FILE"'
    # Build the image
    - docker build --cache-from $CONTAINER_DEVEL_IMAGE -f build/Dockerfile -t $CONTAINER_TEST_IMAGE -t $CONTAINER_DEVEL_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_DEVEL_IMAGE
    # Cache workaround for dind
    - '[ -f "$IMAGE_FILE" ] || docker save -o "$IMAGE_FILE" "$CONTAINER_DEVEL_IMAGE"'

distribute dockerhub:
  stage: distribute
  before_script:
  - echo "using Docker user $DOCKERHUB_USER"
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD docker.io
  variables:
    IMAGE_COMMIT: gamepod/agent:$CI_COMMIT_REF_SLUG
    IMAGE_DEVEL: gamepod/agent:devel
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $IMAGE_COMMIT
  - docker push $IMAGE_COMMIT
  - docker tag $CONTAINER_TEST_IMAGE $IMAGE_DEVEL
  - docker push $IMAGE_DEVEL

release dockerhub:
  stage: release
  only:
  - tags
  before_script:
  - echo "using Docker user $DOCKERHUB_USER"
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD docker.io
  variables:
    IMAGE_TAGGED: gamepod/agent:$CI_COMMIT_TAG
    IMAGE_LATEST: gamepod/agent:latest
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $IMAGE_TAGGED
  - docker push $IMAGE_TAGGED
  - docker tag $CONTAINER_TEST_IMAGE $IMAGE_LATEST
  - docker push $IMAGE_LATEST

release docker:
  stage: release
  only:
  - tags
  script:
    # push the latest image
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_VERSIONED
    - docker push $CONTAINER_RELEASE_VERSIONED
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
