apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamepod-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gamepod-operator
  template:
    metadata:
      labels:
        name: gamepod-operator
    spec:
      serviceAccountName: gamepod-operator
      containers:
        - name: gamepod-operator
          # Replace this with the built image name
          image: gamepod/agent:latest
          command:
          - gamepod-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gamepod-operator"
