// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServer":       schema_pkg_apis_gamepod_v1alpha1_GameServer(ref),
		"gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerSpec":   schema_pkg_apis_gamepod_v1alpha1_GameServerSpec(ref),
		"gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerStatus": schema_pkg_apis_gamepod_v1alpha1_GameServerStatus(ref),
	}
}

func schema_pkg_apis_gamepod_v1alpha1_GameServer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GameServer is the Schema for the gameservers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerSpec", "gamepod.cc/agent/pkg/apis/gamepod/v1alpha1.GameServerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gamepod_v1alpha1_GameServerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GameServerSpec defines the desired state of GameServer",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_gamepod_v1alpha1_GameServerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GameServerStatus defines the observed state of GameServer",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
